spring:
  application:
    name: collie-account
  # datasource:
  #   url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/collie}
  #   username: ${DATABASE_USERNAME:collie}
  #   password: ${DATABASE_PASSWORD:collie}
  #   driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:Y29sbGll}
    password: ${POSTGRES_PASSWORD:Y29sbGll}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account

management:
  endpoints:
    web:
      base-path: /accounts/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka/}

springdoc:
  api-docs:
    path: /accounts/v3/api-docs
  swagger-ui:
    path: /accounts/swagger-ui.html

